name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Dummy Test
      id: dummy-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Dummy Test
        setup-command: ''
        command: sbt 'testOnly testDummy'
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        DUMMY-TEST_RESULTS: "${{steps.dummy-test.outputs.result}}"
      with:
        runners: dummy-test
